easy_admin:
    site_name: '<strong>El blogo</strong>'
    design:
        menu:
            - { label: 'Homepage', route: 'homepage' }
            - User
            - Article
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', type: 'password', label: 'Password' }
                    - { property: 'isActive', type: 'checkbox', label: 'Active?' }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true } }
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'content' }
                    - { property: 'author' }
            edit:
                fields:
                    - { property: 'createdAt' }