security:
    encoders:
        App\Entity\User:
            algorithm: argon2i # TODO Windows, replace "argon2i" by "bcrypt".

    providers:
        app_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: app_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: user_login_form[username]
                password_parameter: user_login_form[password]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin, roles: ROLE_ADMIN }
